apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmChartInflationGenerator:
- chartName: lotus-fullnode
  chartRepoUrl: https://andrestorresgl.github.io/helm-charts
  chartVersion: 0.3.4
  releaseName: lotus-fullnode
  releaseNamespace: lotus-kustomization
  values: values.yaml